<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Gloify-Tech" failures="1" tests="1" name="com.inventsuite.testscript.profilepage.profiletestcase32" time="33.897" errors="0" timestamp="2023-03-13T15:46:06 IST" skipped="0">
  <testcase classname="com.inventsuite.testscript.profilepage.profiletestcase32" name="profiletestcase32" time="33.897">
    <failure message="expected [New Password and Confirm password not matched] but found [[[ChromeDriver: chrome on WINDOWS (f6c5f0a1f055f0bd099ad0670d953af4)] -&gt; xpath: //span[normalize-space()=&#039;New Password and Confirm password not matched&#039;]]]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [New Password and Confirm password not matched] but found [[[ChromeDriver: chrome on WINDOWS (f6c5f0a1f055f0bd099ad0670d953af4)] -> xpath: //span[normalize-space()='New Password and Confirm password not matched']]]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:617)
at com.inventsuite.testscript.profilepage.profiletestcase32.profiletestcase32(profiletestcase32.java:48)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- profiletestcase32 -->
  <system-out>
    <![CDATA[changepwd]]>
  </system-out>
</testsuite> <!-- com.inventsuite.testscript.profilepage.profiletestcase32 -->
